-- Add Privy support to users and wallets tables

-- Add privy_id column to users table
ALTER TABLE users ADD COLUMN privy_id VARCHAR(255) UNIQUE;

-- Add wallet_source column to distinguish between Privy and external wallets
-- PRIVY = wallet generated by Privy
-- EXTERNAL = wallet connected externally (Phantom, Solflare, etc.)
ALTER TABLE wallets ADD COLUMN wallet_source VARCHAR(50) NOT NULL DEFAULT 'EXTERNAL';

-- Add chain_type column to distinguish between SVM and EVM wallets
-- SVM = Solana Virtual Machine (Solana)
-- EVM = Ethereum Virtual Machine (Ethereum, Polygon, etc.)
ALTER TABLE wallets ADD COLUMN chain_type VARCHAR(50) NOT NULL DEFAULT 'SVM';

-- Create index for privy_id lookups
CREATE INDEX idx_users_privy_id ON users(privy_id);

-- Create index for wallet_source lookups
CREATE INDEX idx_wallets_wallet_source ON wallets(wallet_source);

-- Create index for chain_type lookups
CREATE INDEX idx_wallets_chain_type ON wallets(chain_type);

